---
title: "LASSO"
output: html_document
date: "2024-07-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, fig.width=8, fig.height=4, warning = F)
options(scipen = 0, digits = 3)  ## controls base R output

## Package setup
if(!require("pacman")) install.packages("pacman")

pacman::p_load(tidyverse, dplyr, ggplot2, data.table, lubridate, plotROC, usmap, glmnet, knitr, xtable, vader, hp)
```

```{r}
#define response variable

cv_data <- read.csv("/Users/W_Chu/Documents/UPenn 2024/Group_6_Project/data/cv_data.csv", header = TRUE, stringsAsFactors = FALSE)

y <- data.matrix(cv_data[, c('likeCount10k')])
  
x <- data.matrix(cv_data[, c('emotion_label', 'emotion_score', 'compound', 'pos', 'neu', 'neg', 'frustration', 'god', 'grievance', 'hate', 'jealousy', 'threat', 'violence', 'toxicity', 'severe_toxicity', 'identity_attack', 'insult', 'threatening')])

```

```{r}
relaxed_lasso_model <- lm(likeCount10k~emotion_label + emotion_score + compound + pos + neu + neg + threat + threatening + frustration + god + grievance + hate + jealousy + violence + toxicity + severe_toxicity + identity_attack + insult, data=cv_data)

final_lasso_model <- step(relaxed_lasso_model, direction = "backward")

summary(final_lasso_model)

plot(final_lasso_model)
```
```{r}
library(stargazer)

stargazer(final_lasso_model, type = "text")
```


```{r}
library(glmnet)

x <- data.matrix(cv_data[, c('emotion_label', 'emotion_score', 'compound', 'pos', 'threat', 'threatening', 'frustration', 'god', 'toxicity', 'identity_attack', 'insult')])

y <- data.matrix(cv_data[, c('likeCount10k')])

set.seed(1)
result.lasso <- cv.glmnet(x, y, alpha=1)

plot(result.lasso)
```

```{r}
lambda_11 <- cv_fit$lambda.1se

coef <- predict(result.lasso, s=lambda_11, type="coefficients")

coef(result.lasso, s="lambda.min")
significant_variables <- rownames(coef)[which(coef != 0)]
print(significant_variables)

```