---
title: "Neural Network"
author: "Annika Hambali"
date: "2024-07-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache.lazy = FALSE) # notice cache=T here
knitr::opts_chunk$set(fig.height=4, fig.width=7, fig.align = 'center', warning = F)

if(!require('pacman')) {
  install.packages('pacman')
}
pacman::p_load(ggplot2, dplyr, tidyverse, gridExtra, ggrepel, plotly, skimr, latex2exp, data.table, tensorflow, keras) 
```

```{r}
cv_data <- read.csv("data/cv_data.csv")
valid_data <- read.csv("data/valid_data.csv")
```

Virtual Environment

```{r}
reticulate::conda_create("project")
```

Tensorflow and Keras

```{r, eval=FALSE}
if(!require("tensorflow"))
  remotes::install_github("rstudio/tensorflow")
library(tensorflow)
install_tensorflow(envname="project")
```

```{r eval = FALSE}
if(!require("keras"))
  devtools::install_github("rstudio/keras")
library(keras)
install_keras(envname="project")
```

```{r}
use_condaenv("project", required=TRUE)
```

Splitting Data

```{r}
y_train <- data.matrix(cv_data[, c('likeCount10k')])
x_train <- data.matrix(cv_data[, c('emotion_label', 'emotion_score', 'compound', 'pos', 'neu', 'neg', 'frustration', 'god', 'grievance', 'hate', 'jealousy', 'threat', 'violence', 'toxicity', 'severe_toxicity', 'identity_attack', 'insult', 'threatening')])

y_val <- data.matrix(valid_data[, c('likeCount10k')])
x_val <- data.matrix(valid_data[, c('emotion_label', 'emotion_score', 'compound', 'pos', 'neu', 'neg', 'frustration', 'god', 'grievance', 'hate', 'jealousy', 'threat', 'violence', 'toxicity', 'severe_toxicity', 'identity_attack', 'insult', 'threatening')])
```

Building Neural Network
```{r}
model <- keras_model_sequential() %>% 
  layer_dense(units=1024, activation='relu', input_shape=ncol(x_train)) %>% 
  layer_dropout(rate=0.3) %>%
  layer_dense(units=512, activation='relu') %>% 
  layer_dropout(rate=0.3) %>% layer_dense(units=256, activation='relu') %>%
  layer_dropout(rate=0.3) %>% 
  layer_dense(units=128, activation='relu') %>% 
  layer_dropout(rate=0.3) %>% 
  layer_dense(units=64, activation='relu') %>% 
  layer_dropout(rate=0.3) %>% 
  layer_dense(units=32, activation='relu') %>% 
  layer_dropout(rate=0.3) %>% 
  layer_dense(units=16, activation='relu') %>% 
  layer_dropout(rate=0.3) %>% 
  layer_dense(units=1)
```

```{r}
model %>% 
  compile(
    optimizer="adam",
    loss="mean_squared_error",
    metrics=c("mean_absolute_error")
  )
```

```{r}
mod_fit <- model %>% 
  fit(
    x_train, y_train,
    epochs=100,
    batch_size=32,
    validation_data=list(x_val, y_val)
  )

plot(mod_fit)
```

Model Performance
```{r}
model.pred <- predict(model, x_val)

mse <- mean((model.pred - y_val)^2)
mse
```
model.pred <- predict(model, valid_data)
error_model.final <- mean((valid_data$likeCount10k-model.pred)^2)
error_model

results <- model %>% 
  evaluate(
    x_val, y_val
  )
results